/*
 * Copyright 2025 coze-dev Authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Code generated by MockGen. DO NOT EDIT.
// Source: search.go
//
// Generated by this command:
//
//	mockgen -destination ../../../../internal/mock/domain/memory/database/crossdomain/search.go --package database -source search.go
//

// Package database is a generated GoMock package.
package database

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"

	entity "github.com/coze-dev/coze-studio/backend/domain/search/entity"
)

// MockResourceDomainNotifier is a mock of ResourceDomainNotifier interface.
type MockResourceDomainNotifier struct {
	ctrl     *gomock.Controller
	recorder *MockResourceDomainNotifierMockRecorder
}

// MockResourceDomainNotifierMockRecorder is the mock recorder for MockResourceDomainNotifier.
type MockResourceDomainNotifierMockRecorder struct {
	mock *MockResourceDomainNotifier
}

// NewMockResourceDomainNotifier creates a new mock instance.
func NewMockResourceDomainNotifier(ctrl *gomock.Controller) *MockResourceDomainNotifier {
	mock := &MockResourceDomainNotifier{ctrl: ctrl}
	mock.recorder = &MockResourceDomainNotifierMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockResourceDomainNotifier) EXPECT() *MockResourceDomainNotifierMockRecorder {
	return m.recorder
}

// PublishResources mocks base method.
func (m *MockResourceDomainNotifier) PublishResources(ctx context.Context, event *entity.ResourceDomainEvent) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PublishResources", ctx, event)
	ret0, _ := ret[0].(error)
	return ret0
}

// PublishResources indicates an expected call of PublishResources.
func (mr *MockResourceDomainNotifierMockRecorder) PublishResources(ctx, event any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PublishResources", reflect.TypeOf((*MockResourceDomainNotifier)(nil).PublishResources), ctx, event)
}
